# QUESTION 2
# ==========

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

    # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

total = 0

term_one = 1
term_two = 2

while term_one <= 4000000:

    if not term_one % 2:
        total += term_one
    
    temp = term_one
    term_one = term_two
    term_two = term_two + temp

print total